export const SKIN_TYPES = {
  oily: {
    label: 'Oily Skin',
    labelRu: 'Жирная кожа',
    emoji: '✦',
    color: '#9AB592',
    bg: '#E8EDE6',
    accent: '#6E9465',
    description:
      'Your skin produces excess sebum, giving it a characteristic shine — especially in the T-zone. This type is prone to enlarged pores and occasional breakouts, but ages beautifully.',
    traits: ['Visible shine by midday', 'Enlarged pores', 'Prone to blackheads', 'Makeup slides off easily'],
    tips: [
      'Use a gentle foaming or gel cleanser twice daily',
      'Choose oil-free, non-comedogenic moisturizers',
      'Incorporate niacinamide to regulate sebum',
      'Clay masks 1–2× per week to purify pores',
      'Never skip moisturizer — dehydration worsens oil production',
    ],
    ingredients: ['Niacinamide', 'Salicylic Acid', 'Zinc', 'Hyaluronic Acid', 'Green Tea Extract'],
  },
  dry: {
    label: 'Dry Skin',
    labelRu: 'Сухая кожа',
    emoji: '◈',
    color: '#C47D62',
    bg: '#F9EDE8',
    accent: '#A8927F',
    description:
      'Your skin produces less sebum than it needs, which can leave it feeling tight, rough, or flaky. Dry skin craves moisture and responds beautifully to rich, nourishing formulas.',
    traits: ['Tight feeling after cleansing', 'Flakiness or rough patches', 'Barely visible pores', 'Prone to fine lines'],
    tips: [
      'Use a creamy, hydrating cleanser — avoid foaming formulas',
      'Apply a rich moisturizer while skin is still slightly damp',
      'Layer hydration: serum first, then cream',
      'Use a humidifier in dry or heated environments',
      'Exfoliate gently 1× per week to remove flaky cells',
    ],
    ingredients: ['Ceramides', 'Hyaluronic Acid', 'Squalane', 'Shea Butter', 'Glycerin'],
  },
  normal: {
    label: 'Normal Skin',
    labelRu: 'Нормальная кожа',
    emoji: '◇',
    color: '#8A7260',
    bg: '#FAF5EE',
    accent: '#5C4A3A',
    description:
      'Your skin is beautifully balanced — not too oily, not too dry. Pores are small, texture is smooth, and blemishes are rare. Focus on maintaining this equilibrium.',
    traits: ['Small, barely visible pores', 'Smooth, even texture', 'Rarely oily or dry', 'Minimal sensitivity'],
    tips: [
      'Maintain a consistent, simple routine',
      'Use a balanced cleanser — gel or milk works well',
      'Light to medium moisturizer daily',
      'SPF 30+ is non-negotiable',
      'Antioxidant serums (Vitamin C) help preserve balance',
    ],
    ingredients: ['Vitamin C', 'Retinol', 'Peptides', 'SPF', 'Antioxidants'],
  },
  combination: {
    label: 'Combination Skin',
    labelRu: 'Комбинированная кожа',
    emoji: '⬡',
    color: '#7B9BB5',
    bg: '#E8F0F5',
    accent: '#4A7A9B',
    description:
      'You have an oily T-zone (forehead, nose, chin) with normal or dry cheeks. This is the most common skin type and responds well to targeted, zone-specific care.',
    traits: ['Oily T-zone, dry cheeks', 'Mixed pore sizes', 'Occasional breakouts on forehead/nose', 'Dry or tight cheek area'],
    tips: [
      'Use a balanced gel-cream cleanser',
      'Apply lighter moisturizer on T-zone, richer on cheeks',
      'Spot-treat oily areas with niacinamide',
      'Clay masks only on T-zone, hydrating masks on cheeks',
      'Avoid heavy, pore-clogging products',
    ],
    ingredients: ['Niacinamide', 'Hyaluronic Acid', 'BHA (T-zone)', 'Ceramides (cheeks)', 'Retinol'],
  },
}

export const LIFESTYLE_QUESTIONS = [
  {
    id: 'water_intake',
    section: 'Hydration',
    question: 'How much water do you drink daily?',
    type: 'select',
    options: [
      { value: 'less_1l', label: 'Less than 1 litre' },
      { value: '1_2l', label: '1–2 litres' },
      { value: '2_3l', label: '2–3 litres' },
      { value: 'more_3l', label: 'More than 3 litres' },
    ],
  },
  {
    id: 'sleep_hours',
    section: 'Sleep',
    question: 'How many hours do you sleep on average?',
    type: 'select',
    options: [
      { value: 'less_5', label: 'Less than 5 hours' },
      { value: '5_7', label: '5–7 hours' },
      { value: '7_9', label: '7–9 hours' },
      { value: 'more_9', label: 'More than 9 hours' },
    ],
  },
  {
    id: 'diet',
    section: 'Diet',
    question: 'How would you describe your diet?',
    type: 'select',
    options: [
      { value: 'processed', label: 'Mostly processed / fast food' },
      { value: 'mixed', label: 'Mixed — some healthy, some not' },
      { value: 'balanced', label: 'Balanced and varied' },
      { value: 'plant_based', label: 'Plant-based / whole foods' },
    ],
  },
  {
    id: 'stress_level',
    section: 'Stress',
    question: 'How would you rate your daily stress level?',
    type: 'scale',
    min: 1,
    max: 5,
    labels: ['Very low', 'Low', 'Moderate', 'High', 'Very high'],
  },
  {
    id: 'sun_exposure',
    section: 'Sun & Environment',
    question: 'How much time do you spend outdoors daily?',
    type: 'select',
    options: [
      { value: 'minimal', label: 'Minimal (mostly indoors)' },
      { value: '30_60min', label: '30–60 minutes' },
      { value: '1_3h', label: '1–3 hours' },
      { value: 'more_3h', label: 'More than 3 hours' },
    ],
  },
  {
    id: 'spf_use',
    section: 'Sun & Environment',
    question: 'Do you use sunscreen regularly?',
    type: 'select',
    options: [
      { value: 'never', label: 'Never' },
      { value: 'sometimes', label: 'Sometimes' },
      { value: 'often', label: 'Often' },
      { value: 'always', label: 'Every day, always' },
    ],
  },
  {
    id: 'exercise',
    section: 'Activity',
    question: 'How often do you exercise?',
    type: 'select',
    options: [
      { value: 'rarely', label: 'Rarely or never' },
      { value: '1_2pw', label: '1–2 times per week' },
      { value: '3_5pw', label: '3–5 times per week' },
      { value: 'daily', label: 'Every day' },
    ],
  },
  {
    id: 'current_routine',
    section: 'Skincare',
    question: 'How would you describe your current skincare routine?',
    type: 'select',
    options: [
      { value: 'none', label: 'I don\'t have one' },
      { value: 'basic', label: 'Basic (cleanse + moisturize)' },
      { value: 'moderate', label: 'Moderate (cleanser, serum, SPF)' },
      { value: 'advanced', label: 'Extensive multi-step routine' },
    ],
  },
  {
    id: 'concerns',
    section: 'Skincare',
    question: 'What are your main skin concerns? (choose all that apply)',
    type: 'multi',
    options: [
      { value: 'acne', label: 'Acne & breakouts' },
      { value: 'aging', label: 'Fine lines & aging' },
      { value: 'hyperpigmentation', label: 'Dark spots & uneven tone' },
      { value: 'sensitivity', label: 'Sensitivity & redness' },
      { value: 'dullness', label: 'Dullness & texture' },
      { value: 'pores', label: 'Large pores' },
      { value: 'dehydration', label: 'Dehydration' },
      { value: 'none', label: 'No specific concerns' },
    ],
  },
]
