"""add diary and reviews

Revision ID: 07eb9b969d4c
Revises: 0001
Create Date: 2026-04-03 19:55:12.151150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07eb9b969d4c'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lifestyles_user_id', table_name='lifestyles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_lifestyles_user_id', 'lifestyles', ['user_id'], unique=False)
    # ### end Alembic commands ###
